### ISSUE TITLE
Migrate out of `set-output`

### ISSUE THREAD

**Issue by RichDom2185** [source-academy/frontend#2663] opened 2023-09-04 02:58 UTC
Follows the [deprecation notice](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/).

**Comment by sayomaki** [comment] 2023-09-04 05:39
Might be a duplicate of #2478

**Comment by RichDom2185** [comment] 2023-09-04 05:41
> Might be a duplicate of #2478

Oops, you are right! Totally forgot about this. Thanks!

**Closed** 2023-09-04 05:42 UTC
